# 使用LocalStack 模拟的S3,可以根据不同的ImageStorageProvider实现不同的图片存储
[S3]
AK = test
SK = test
BUCKET_NAME = test-bucket
ENDPOINT = http://localstack:4566
# 暴露出去的域名
OUT_ENDPOINT = http://docparse.bella.top:4566

[KAFKA]
file_api_servers = kafka:29092
file_api_topic = bella-file-broadcast

 # [你部署的FILE_API地址]
[FILEAPI]
URL = ""

[OCR]
model_name = Doubao-1.5-vision-pro-32k
enable = True

[LOG]
dir = /applogs
log_file = app.log

[SUPPORTED_FILE_TYPES]
# 支持的文件类型，用逗号分隔
types = doc,pptx,pdf,csv,xlsx,xls,txt,md,json,jsonl,py,c,cpp,java,js,sh,xml,yaml,html,png,jpeg,jpg,bmp