name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  REGISTRY: docker.io
  IMAGE_NAME: bellatop/document_parse
  
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - name: Set date tag
      id: date
      run: echo "TAG=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}   
        password: ${{ secrets.DOCKERHUB_TOKEN }}      
    - name: Build & push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.TAG }}
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /docker-compose
            export IMAGE_TAG=latest           
            docker-compose pull                        
            docker-compose up -d --build               
            docker image prune -af                     
